#!/bin/bash
set -eu

TF_VERSION=1.3.2

docker run -it --rm \
  -v $PWD:/tmp \
  -w=/tmp \
  -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
  -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
  hashicorp/terraform:$TF_VERSION $@